services:
    hangman.controller.slack:
        class: Webberig\SlackHangBot\Controller\Slack
        scope: request
        arguments:
             - @hangman.service.command_handler
#            - @templating
#            - @router